
configdb:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Pass: **************1.
  Schema:
#   程序基本信息表
    App: chengken.starrocks_information_slowconfig
    Connect: chengken.starrocks_information_connections
    Robot: chengken.starrocks_information_larkrobot
#    短查询保障，资源隔离short query类型语句的保障，struct请参考exec.sql
#    ShortQuery: chengken.starrocks_information_shortconfig
#    starrocks_information_slowconfig表中slow_query_metaapp字段代表元数据名称，物理机与用户关联表
#    表建在StarRocks集群中，struct请参考exec.sql
#    IpSystem: ops.ops_starrocks_ip_system
#    starrocks_information_slowconfig表中slow_query_metaapp字段代表元数据名称，内部人员飞书信息表
#    表建在StarRocks集群中，struct请参考exec.sql
#    LarkMeta: ops.feishu_user_information

# 当运行调试模式时，可以将告警对接到下面的飞书群
# 从而不走global设置
mode:
  cronsyntax: '*/1 * * * *'
#  Debug: xxx
#  Info: xxx

# 主题域
#domain:
#  AppKey: xxx
#  Sign: xxx
#  WorksheetId: xxx
#  Uri: xxx

logger:
  LogPath: /u/users/svccndlopsns/chengken/log/StarRocksSupport
  LogLevel: 0
  MaxSize: 0
  MaxBackups: 0
  MaxAge: 0
  Compress: false
  JsonFormat: false
  ShowLine: true
  LogInConsole: true

